"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { QueryClientProvider } from "react-query";
import queryClient from "@/utils/queryClient";
import { ApolloProvider } from '@apollo/client';
import clients from "./graph";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FlipGrid",
  description: "Generated by MahaDevs",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ApolloProvider client={clients}>
      <html>
        <body className={inter.className}>
          <div className="max-w-screen bg-[#f2f2f2] overflow-hidden">
            {/* <Navbar></Navbar> */}
            {children}
          </div>
        </body>
      </html>
      </ApolloProvider>
  );
}
