import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './Components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'FlipGrid',
  description: 'Generated by MahaDevs',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html >
      <body className={inter.className} >
        <div className='min-h-screen'>
            <Navbar></Navbar>
            {children}
            </div></body>
    </html>
  )
}
